// Writes src/fonts.js with the Geist fonts (SIL Open Font License 1.1) as base64, so the PDF
// renderer never needs to fetch a font.
import { readFileSync, writeFileSync } from "node:fs";
const b64 = (f) => readFileSync(new URL(`../assets/${f}`, import.meta.url)).toString("base64");
writeFileSync(new URL("../src/fonts.js", import.meta.url),
  `// Generated by tools/build_fonts.mjs. Geist and Geist Mono, SIL Open Font License 1.1 (assets/LICENSE.geist-fonts.txt).\nexport const FONTS = { sans: "${b64("Geist-Variable.woff2")}", mono: "${b64("GeistMono-Variable.woff2")}" };\n`);
console.log("fonts.js written");
