// hs-ccdb-mcp offline test: a fake hs-jccdb-obs service binding, no network.
import worker from "../src/worker.js";
import { readFileSync } from "node:fs";
let fail = 0;
const chk = (n, c, x = "") => { console.log((c ? "PASS  " : "FAIL  ") + n + (c ? "" : "  <<< " + String(x).slice(0, 200))); if (!c) fail++; };
const DASH = /[–—―]/;
let lastCall = null;
const env = { JCCDB_SVC: { fetch: async (url, init) => {
  const b = JSON.parse(init.body); lastCall = { url: String(url), name: b.params.name, args: b.params.arguments };
  if (b.params.name === "jccdb_labor_rate") return new Response(JSON.stringify({ jsonrpc: "2.0", id: 1, result: { structuredContent: { count: 1, rows: [{ pref: "奈良県", job: "大工", wage: 27000 }] } } }));
  if (b.params.name === "jccdb_us_prices") return new Response(JSON.stringify({ jsonrpc: "2.0", id: 1, result: { isError: true, structuredContent: { error: "unknown region", code: "unknown_region", invalid_argument: true } } }));
  if (b.params.name === "jccdb_coverage") throw new Error("down");
  return new Response("not json");
} } };
const post = async (body, e = env) => worker.fetch(new Request("https://ccdb.horizonshield.dev/mcp", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }), e);
const rpc = async (method, params, e) => (await (await post({ jsonrpc: "2.0", id: 1, method, params }, e)).json());

const init = (await rpc("initialize", { protocolVersion: "2025-06-18", capabilities: {}, clientInfo: { name: "t", version: "0" } })).result;
chk("initialize echoes a supported protocol version", init.protocolVersion === "2025-06-18");
chk("an unknown protocol version gets 2025-06-18", (await rpc("initialize", { protocolVersion: "1999-01-01" })).result.protocolVersion === "2025-06-18");
chk("instructions name JCCDB, USCCDB and point fair-price checks to hs-mcp", /JCCDB/.test(init.instructions) && /USCCDB/.test(init.instructions) && init.instructions.includes("https://mcp.horizonshield.dev/mcp"));
chk("instructions have no dashes", !DASH.test(init.instructions));
const tl = (await rpc("tools/list", {})).result.tools;
const served = JSON.parse(readFileSync(new URL("../build/data_tools.json", import.meta.url), "utf8"));
chk("15 tools", tl.length === 15, tl.length);
chk("tool definitions are byte for byte the ones hs-mcp served", JSON.stringify(tl) === JSON.stringify(served));
chk("every tool has outputSchema, title and readOnlyHint true", tl.every((t) => t.outputSchema && t.title && t.annotations && t.annotations.readOnlyHint === true));
chk("every parameter has a description", tl.every((t) => Object.values((t.inputSchema && t.inputSchema.properties) || {}).every((p) => typeof p.description === "string" && p.description.length > 0)));
const ok = (await rpc("tools/call", { name: "get_jccdb_labor_rate", arguments: { pref: "奈良県", job: "大工" } })).result;
chk("a call is forwarded to jccdb-obs.internal under the obs name", lastCall.url === "https://jccdb-obs.internal/mcp" && lastCall.name === "jccdb_labor_rate" && lastCall.args.job === "大工");
chk("success: structuredContent with fetch_failed false and no isError", !ok.isError && ok.structuredContent.fetch_failed === false && ok.structuredContent.count === 1);
const bad = (await rpc("tools/call", { name: "get_us_construction_prices", arguments: { state: "Atlantis" } })).result;
chk("an argument error stays invalid_argument, fetch_failed false", bad.isError && bad.structuredContent.invalid_argument === true && bad.structuredContent.fetch_failed === false && bad.structuredContent.error === "unknown_region");
const down = (await rpc("tools/call", { name: "get_jccdb_coverage", arguments: {} })).result;
chk("a failed lookup is fetch_failed true, not zero rows", down.isError && down.structuredContent.fetch_failed === true && down.structuredContent.count === undefined);
const junk = (await rpc("tools/call", { name: "get_us_permits", arguments: {} })).result;
chk("an unreadable answer is fetch_failed true", junk.isError && junk.structuredContent.fetch_failed === true);
const unb = (await rpc("tools/call", { name: "get_us_permits", arguments: {} }, {})).result;
chk("no binding is fetch_failed true", unb.isError && unb.structuredContent.error === "jccdb_obs_not_bound");
const unk = (await rpc("tools/call", { name: "audit_estimate", arguments: {} })).result;
chk("a fair-price tool is not here and the answer points to hs-mcp", unk.isError && unk.structuredContent.message.includes("https://mcp.horizonshield.dev/mcp"));
const long = (await rpc("tools/call", { name: "get_jccdb_labor_rate", arguments: { job: "x".repeat(16001) } })).result;
chk("an oversized argument is refused before forwarding", long.isError && long.structuredContent.error === "input_too_long");
const note = await post({ jsonrpc: "2.0", method: "notifications/initialized" });
chk("a notification gets 202 and no body", note.status === 202 && (await note.text()) === "");
chk("an unknown method is -32601", (await rpc("nope", {})).error.code === -32601);
const batch = await (await post([{ jsonrpc: "2.0", id: 1, method: "ping" }, { jsonrpc: "2.0", method: "notifications/initialized" }])).json();
chk("a batch answers requests and skips notifications", Array.isArray(batch) && batch.length === 1 && batch[0].id === 1);
const info = await (await worker.fetch(new Request("https://ccdb.horizonshield.dev/"), env)).json();
chk("GET / lists the tools and the datasets", info.tools.length === 15 && info.datasets.usccdb && info.fair_price_checks);
const h = await (await worker.fetch(new Request("https://ccdb.horizonshield.dev/health"), env)).json();
chk("GET /health", h.ok === true && h.tools === 15 && h.bound === true);
chk("CORS on POST", (await post({ jsonrpc: "2.0", id: 1, method: "ping" })).headers.get("access-control-allow-origin") === "*");
console.log(fail ? fail + " FAIL" : "hs-ccdb-mcp: ALL PASS");
process.exit(fail ? 1 : 0);
